//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int StatusID { get; set; }
        public int PriorityID { get; set; }
        public int AssigneeID { get; set; }
        public int AssignerID { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual TaskPriority TaskPriority { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
